# Generated by Django 5.2.4 on 2025-07-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Кімната', 'verbose_name_plural': 'Кімнати'},
        ),
        migrations.AlterModelOptions(
            name='typeroom',
            options={'verbose_name': 'Тип кімнати', 'verbose_name_plural': 'Тип кімнат'},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Номер кімнати:'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.typeroom', verbose_name='Тип кімнати:'),
        ),
        migrations.AlterField(
            model_name='typeroom',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис кімнати:'),
        ),
        migrations.AlterField(
            model_name='typeroom',
            name='name',
            field=models.CharField(verbose_name='Тип кімнати:'),
        ),
    ]
